Importing Libraries and reading datasets

In [ ]:
import pandas as pd
df = pd.read_csv('dataset.csv')
df.head()

,Temperature(C),Humidity,AQI,Wind speed kmph,Atmospheric pressure(hPa),Latitude(N),Longitude(E),Allergy
0,32,76,120,4,1008.5,12.9165,79.1325,0
1,22,55,100,12,1007.4,12.9165,79.1325,1
2,34,45,135,5,1005.0,12.9165,79.1325,0
3,20,30,70,3,1005.0,12.9165,79.1325,0

In [ ]:
# data ko divide kar rahe hai 'input ' aur output(target) mai
# dataframe se Allergy column chhd kar baaki ko input m store kiya
inputs=df.drop(['Allergy'],axis='columns')
# dataframe se allergy waala column ko target variable m store kar diya
target=df['Allergy']

In [ ]:
inputs

,Temperature(C),Humidity,AQI,Wind speed kmph,Atmospheric pressure(hPa),Latitude(N),Longitude(E)
0,32,76,120,4,1008.5,12.9165,79.1325
1,22,55,100,12,1007.4,12.9165,79.1325
2,34,45,135,5,1005.0,12.9165,79.1325
3,20,30,70,3,1005.0,12.9165,79.1325

In [ ]:
target

0    0
1    1
2    0
3    0
Name: Allergy, dtype: int64

In [ ]:
# sklearn library se train test_split use karke input aur target ko split kar rahe hai(train aur test)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(inputs,target,test_size=0.2)
#testsize =0.2 matlab 20 percent data will become  test data and 80 percent training data

In [ ]:
#sklearn library se Random forest classifier import kar rahe hai aur apne model ko create kar rahe hai

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=5)# estimators matlab kitna trees hone chahiye in the Random forest
model.fit(x_train,y_train)

In [ ]:
model.score(x_test,y_test) #model ka accuracy check karne ke liye

In [ ]:
pip install pyrebase  # yeh library firebase use karne ke liye hai
# yeh library pehle install karna padhta hai

In [ ]:
import pyrebase 
# config mai apne firebase account ka info hai jo connection karne ke liye zaroori hai 
config={
    "apiKey": "AIzaSyCi1LuLjxo75ZowHB6NVFH_WH7GXMTLCHU",
  "authDomain": "safe-51344.firebaseapp.com",
  "databaseURL": "https://safe-51344-default-rtdb.firebaseio.com",
  "projectId": "safe-51344",
  "storageBucket": "safe-51344.appspot.com",
  "messagingSenderId": "316714398132",
  "appId": "1:316714398132:web:c9c3eb61dff6b1efc702e1",
  "measurementId": "G-JSEYM0HQT3"
}
#apne firebase account ko connect kar rahe hai
firebase=pyrebase.initialize_app(config)
#database se connect kar rage hai
database=firebase.database()

In [ ]:
import csv # data ko csv format m convert karne ke liye 
import codecs # iss library mai encoders aur decoders hote hai to convert from one file fromat to other (eg json to CSV)
import urllib.request # internt se connect karne ke liye aur http request bhejne ke liye
import urllib.error  #request bhejne mai koi error aaya toh iss libarary mai error handling functions hai
import sys   #runtime environment ko control karne ke liye (eg agar code ko execeute hone se rokna ho toh sys.exit)
while True:
  # pehle apne sensor ka data kheech lenge
  value=database.child("sensorData").get().val()
  # sensor data se latitude aur longitude nikaal kar wind speed aur atmospheric pressure nikaalenge.....
  #....using weather.visualcrossing website/API
  
  #base url hai api ka main link jisme baaki information hamko jod kar bhejna hai
  BaseURL = 'https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/'
  ApiKey='JA9RQVJ6KWN8T32GP7BXMETMB'
  #UnitGroup sets the units of the output - us or metric
  UnitGroup='us'
  #getting the Location for the weather data from the database
  Location=str(value['Latitude'])+","+str(value['Longitude'])
  from datetime import date
  today = date.today()
  d1 = today.strftime("%Y-%m-%d")
  StartDate = d1
  EndDate=d1 #start aur end date same hai kyuki bas aaj ka information chahiye
  ContentType="csv"
  Include="days"
  # base url mai location data jod rahe hai
  ApiQuery=BaseURL + Location
  #append the start and end date if present
  if (len(StartDate)):
      ApiQuery+="/"+StartDate
      if (len(EndDate)):
          ApiQuery+="/"+EndDate
 #baaki ka values bhi jod rahe hai url mai
  #Url is completed. Now add query parameters (could be passed as GET or POST)
  ApiQuery+="?"
  #append each parameter as necessary
  if (len(UnitGroup)):
      ApiQuery+="&unitGroup="+UnitGroup
  if (len(ContentType)):
      ApiQuery+="&contentType="+ContentType
  if (len(Include)):
      ApiQuery+="&include="+Include
  ApiQuery+="&key="+ApiKey
  # API mai apna request bhej rahe hai
  try: 
      CSVBytes = urllib.request.urlopen(ApiQuery)
  except urllib.error.HTTPError  as e:
      ErrorInfo= e.read().decode() 
      print('Error code: ', e.code, ErrorInfo)
      sys.exit()
  except  urllib.error.URLError as e:
      ErrorInfo= e.read().decode() 
      print('Error code: ', e.code,ErrorInfo)
      sys.exit()
  # Parse the results as CSV using CSV  library
  CSVText = csv.reader(codecs.iterdecode(CSVBytes, 'utf-8'))
  RowIndex = 0
  # The first row contain the headers and the additional rows each contain the weather metrics for a single day
  # To simply our code, we use the knowledge that column 0 contains the location and column 1 contains the date.  The data starts at column 4
  # weather API ke output se apne kaam ka values nikaal kar databse mai bhej rahe hai
  for Row in CSVText:
      if RowIndex == 0:
          FirstRow = Row
      else:
          print('Weather in ', Row[0], ' on ', Row[1])

          ColIndex = 0
          for Col in Row:
              if ColIndex == 17 :
                  print('   ', FirstRow[ColIndex], ' = ', Row[ColIndex])
                  database.child("sensorData").child("Wind speed").set(float(Row[ColIndex]))
              if ColIndex == 19 :
                  print('   ', FirstRow[ColIndex], ' = ', Row[ColIndex])
                  database.child("sensorData").child("Atmospheric pressure").set(float(Row[ColIndex]))
              ColIndex += 1
      RowIndex += 1
  # If there are no CSV rows then something fundamental went wrong
  if RowIndex == 0:
      print('Sorry, but it appears that there was an error connecting to the weather server.')
      print('Please check your network connection and try again..')

  # If there is only one CSV  row then we likely got an error from the server
  if RowIndex == 1:
      print('Sorry, but it appears that there was an error retrieving the weather data.')
      print('Error: ', FirstRow)
  value=database.child("sensorData").get().val()
  q=list(value.values())
  allergyPrediction=int(model.predict([q]))
  database.child("AllergyPrediction").set(allergyPrediction)
  allergyPrediction
  time.sleep(1) # Sleep for 5 second